apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Developer\Downloads\kompose-windows-amd64.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: broker
  name: broker
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "9101"
      port: 9101
      targetPort: 9101
  selector:
    io.kompose.service: broker
status:
  loadBalancer: {}
