apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Developer\Downloads\kompose-windows-amd64.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: connect
  name: connect
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
  selector:
    io.kompose.service: connect
status:
  loadBalancer: {}
