apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Developer\Downloads\kompose-windows-amd64.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: schema-registry
  name: schema-registry
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: schema-registry
status:
  loadBalancer: {}
